<h1> 분석 기법 - Vector space model </h1>
- 문서를 bag-of-model로 표현해 보자.
- 표현된 bag-of-model로 간단한 머신러닝 알고리즘을 적용해보자
- TF-IDF를 통해 중요한 단어를 추출해보자.

In [3]:
# kkma package

from konlpy.tag import Kkma
from konlpy.utils import pprint

news1 = """
중국이 관영매체를 통해 미국 공화당 대선후보인 도널드 트럼프가 떨어지는 지지도를 만회하기 위해 '중국 때리기 카드'를 쓰고 있다고 반박에 나섰다.
관영 신화통신은 9일 논평을 통해 트럼프의 선동적인 수사는 '미국 중서부 블루칼라 유권자에게 어필하려는 의도'라며 "위험하고 미·중 양국관계에 아무런 실질적 도움이 안 된다"고 주장했다.
트럼프 후보는 전날 미국 디트로이트에서 경제공약을 발표하면서 "중국이 미국과 교역에서 상상할 수 있는 모든 방법으로 기존의 룰을 깨고 있고 미국 재정적자의 절반가량은 중국의 책임"이라고 주장했다.
트럼프는 이어 중국이 불법적으로 수출 보조금을 지급하고 위안화 환율을 조작하고 있으며 지적재산권을 훔치고 있다고 비난을 퍼부었다.
그는 중국의 수출품을 차단하고 세계 무역규정을 재협상함으로써 미국경제를 부흥시켜야 한다며 "글로벌리즘이 아닌 아메리카니즘(Americanism)이 우리의 신조가 될 것"이라고 강조했다.
신화통신은 이에 대해 "트럼프와 그의 팀이 미국의 경제 부진에 대해 중국과 세계 자유무역을 희생양으로 삼음으로써 자유무역주의라는 공화당의 전통 정신을 위배하고 있다"고 반박했다.
그러면서 미국 정치인들의 '중국 때리기'는 미국 자체의 구조적 퇴보를 숨기려 노상 행해졌던 일이라고 지적했다. 신화통신은 이어 미국이 이런 문제를 해결하려면 뼈를 깎는 구조조정이 필요하다고 조언하기도 했다.
신화통신은 또 미국 상무부의 통계를 인용해 트럼프식 접근법으로는 미국 내 350만 개 일자리가 희생될 것이고 경제침체와 함께 미국 소비자들이 더 비싸게 물건을 사야 하는 결과를 초래할 뿐이라고 강조했다.
지난해 대미 무역수지 흑자만 3천700억 달러를 낸 중국은 트럼프 후보뿐 힐러리 클린턴 민주당 대선 후보도 보호무역 강화 기조의 선거공약을 내놓자 이들 후보의 공약이 대선 후 현실화될지에 촉각을 곤두세우고 있다.
AP통신은 이날 신화통신의 반박 논평 소식을 전하며 선거유세 기간 트럼프 후보의 중국에 대한 비판이 공산당 일당독재의 정치체제나 인권 남용에 대한 언급은 거의 없이 중국의 무역관행에만 초점을 맞추고 있다고 지적했다.
"""

# 명사만 추출해보자 - 
kkma = Kkma()
news1_pos = kkma.pos(news1)

In [4]:
import nltk # 형태소 분석할 떄 데이터 탐색할 때 사용하면 편리
text = nltk.Text(news1_pos)

In [5]:
print(len(text.tokens))                 # returns number of tokens
print(len(set(text.tokens)))            # returns number of unique tokens
pprint(news1_nouns)    # returns frequency distribution

535
264


NameError: name 'news1_nouns' is not defined

<h3> kkma package vs twitter package</h3>
- kkma의 경우 우리가 알고 있는 품사보다 형태소를 더 작은 단위로 분석 (연구용)
- 배경지식이 없다면 해석하기 힘듬
- 트위터 다니시다가 만든 새로운 형태소 분석 패키지 : twitter

In [2]:
# 대통령 취임사로 tf vector 만들어보기

president_address = open('대통령취임사.2txt.txt','r').read()
# print(president_address)


In [118]:
# Twitter package
from konlpy.tag import Twitter
pos_tagger = Twitter()
pos_address = ['/'.join(t) for t in pos_tagger.pos(president_address) if t[1]=='Noun'] # 형태소로 tokenizing // 동음이의어를 구분하기 좋음
#pos_news = ['/'.join(t) for t in pos_tagger.pos(news1) if t[1]=='Noun']

# list 원소 중 10개를 살펴보기
pprint(pos_address[:10])

['국민/Noun',
 '여러분/Noun',
 '만/Noun',
 '해외동포/Noun',
 '여러분/Noun',
 '저/Noun',
 '오늘/Noun',
 '대한민국/Noun',
 '제/Noun',
 '대통령/Noun']


In [119]:
import nltk 

# Text() - 단일 문서에 대한 탐색에 좋은 함수가 내장
text = nltk.Text(pos_address) # 형태소 분석이 된 list를 input으로 넣어주면


print(len(text.tokens)) # 문서에서 나온 token 수
print(len(set(text.tokens))) # 겹치지 않는 token 개수
pprint(text.vocab().most_common(20)) # 가장 빈번히 나온 token 나열


973
406
[('국민/Noun', 57),
 ('것/Noun', 33),
 ('수/Noun', 28),
 ('우리/Noun', 23),
 ('시대/Noun', 22),
 ('여러분/Noun', 19),
 ('문화/Noun', 18),
 ('저/Noun', 16),
 ('행복/Noun', 15),
 ('대한민국/Noun', 12),
 ('국가/Noun', 12),
 ('새/Noun', 11),
 ('사회/Noun', 10),
 ('경제/Noun', 9),
 ('희망/Noun', 9),
 ('창조경제/Noun', 8),
 ('길/Noun', 8),
 ('세계/Noun', 8),
 ('신뢰/Noun', 8),
 ('정부/Noun', 8)]


In [ ]:
# 빈도 기준으로 token plot - distribution확인
%matplotlib inline 
text.plot(50)

# font 문제가 있다면 먼저 실행
from matplotlib import font_manager, rc
font_fname = 'c:/windows/fonts/NanumGothicLight.ttf'     # A font of your choice
font_name = font_manager.FontProperties(fname=font_fname).get_name()
rc('font', family=font_name)

In [122]:
# FreqDist 함수로도 같은 기능을 수행할 수 있다.
freq = nltk.FreqDist(text)
freq['것/Noun']
freq.most_common(10)
freq.plot(10)

<h3> TF-IDF 벡터 만들기</h3>
- TF 벡터와 TF-IDF 벡터는 scikit learn(http://scikit-learn.org/)을 통해 계산할 수 있다.

In [123]:
# 한글 bag-of-words 만들어보자
from konlpy.tag import Twitter
import pandas as pd

# 연합뉴스 로딩
kor_corpus = pd.read_csv(r'D:\workspace_python\한류_연합뉴스.csv', encoding='cp949')

# 뉴스기사 정제

pos_tagger = Twitter()
#pos_address = ['/'.join(t) for t in pos_tagger.pos(news) if t[1]=='Noun' for news in kor_corpus['contents']] # 형태소로 tokenizing // 동음이의어를 구분하기 좋음


# list 원소 중 10개를 살펴보기
#pprint(pos_address[:10])
total_news = []

# 한글 문서 명사만 뽑아서 tf-idf
stopword = ['것','수','저']
for news in kor_corpus['contents'].head():
    pos_news = ['/'.join(t[:-1]) for t in pos_tagger.pos(news) if ((t[1]=='Noun') & (t[0] not in stopword))]
    total_news.append(' '.join(pos_news))


In [124]:
from sklearn.feature_extraction.text import CountVectorizer

kor_vectorizer = CountVectorizer(min_df=1) # 등장하는 단어들에 대한 오브젝트
kor_bow = kor_vectorizer.fit_transform(total_news) # 딕셔너리에 실제 단어들을 입력


In [125]:
print(kor_vectorizer.get_feature_names())
# bag-of-words
print(kor_bow.shape)
print(kor_bow.toarray())

['가수', '가요', '각각', '개정', '개척', '거점', '건강', '검진', '견실', '견지해', '결정', '경북', '경연', '경우', '경운대', '경쟁', '경제', '경향', '계획', '고고', '고신대', '공간', '공공', '공연장', '공유', '과거', '관계자', '관련', '광부', '광주', '교류', '교육', '교육감', '구미', '구미시장', '구축', '국내', '국립병원', '국민', '국악', '국제', '권정열', '규모', '그룹', '극장', '극히', '근무', '금은', '기기', '기도', '기사', '기술', '기업', '기자', '기존', '기타', '기획', '김영만', '김태우', '끼리', '나라', '날로', '내년', '내달', '내용', '노래', '노아', '누구', '눈길', '능이', '다음', '다이어트', '단일', '당일', '대구', '대부분', '대상', '대중', '대표', '대학', '대한', '대해', '댄스', '더욱', '도시', '도움', '도지사', '독소', '동상', '드림', '등록', '디자이너', '디자인', '라며', '라피', '리밍', '만원', '메시지', '몽골', '문의', '문전', '문화', '물리', '미래', '미사일', '미용', '민간', '박대', '박순', '박창수', '반복', '반응', '발굴', '발급', '발생', '발전', '방어', '배너', '배치', '번역', '베트남', '병원', '보도', '보유', '복부', '복음병원', '본문', '본선', '봉사', '부문', '부분', '부산', '분야', '분위기', '분해', '브랜드', '브리핑', '사드', '사립', '사무국', '사업', '사흘', '산업', '상의', '상표', '생각', '생산', '생소', '서로', '서울', '석션기', '선도', '선발', '설명', '성공', '성분', '성인', '세계', '세라믹', '세종', '센터', '

In [126]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer() # tfidf 변환 오브젝트 생성
tfidf = transformer.fit_transform(kor_bow.toarray())

In [127]:
tfidf.toarray()

array([[ 0.        ,  0.        ,  0.        , ...,  0.06236855,
         0.        ,  0.06236855],
       [ 0.07572825,  0.1514565 ,  0.06109707, ...,  0.        ,
         0.07572825,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.05084439, ...,  0.        ,
         0.        ,  0.        ]])

In [128]:
# tf idf를 이용한 중요 단어 순위
import numpy as np

doc_index = 3

arr = np.array(tfidf.toarray()[doc_index])
idx = (-arr).argsort()[:20]

for i in idx:
    print(kor_vectorizer.get_feature_names()[i])


대구
패션
문화
인문학
극장
패션쇼
회관
차례
한국
예술
행사
최재천
티셔츠
시간
취지
지성
출신
국제
기획
이문열


In [129]:
# 간단한 예제

ex_text = ["한국 김치 ",
          "한국 미국 FTA FTA ",
          "한국 미국 "]

kor_vectorizer = CountVectorizer(min_df=1)
kor_bow = kor_vectorizer.fit_transform(ex_text)

transformer = TfidfTransformer()
tfidf = transformer.fit_transform(kor_bow.toarray())
print(kor_vectorizer.get_feature_names())
print(kor_bow.toarray())
print(tfidf.toarray())


['fta', '김치', '미국', '한국']
[[0 1 0 1]
 [2 0 1 1]
 [0 0 1 1]]
[[ 0.          0.861037    0.          0.50854232]
 [ 0.90100815  0.          0.34261996  0.26607496]
 [ 0.          0.          0.78980693  0.61335554]]


In [ ]:
wordcloud

<h3> 문서 비교 </h3>
- 각각의 문서를 bag-of-words를 이용해 수치형 벡터로 표현
- 문서끼리 얼마나 가까운지 similarity를 계산하여 비교해보자

In [99]:
nltk.Text(pos_news).concordance('김영만', width=50, lines=5)
nltk.Text(pos_news).dispersion_plot(['한국','미사일'])

Displaying 1 of 1 matches:
                       김영만 기자 한국 고고 미사일 방어 체계 사드 


In [96]:
print(pos_news)

['세종', '연합뉴스', '김영만', '기자', '한국', '고고', '미사일', '방어', '체계', '사드', '배치', '결정', '이후', '중국', '내', '한류', '위축', '우려', '대해', '문화', '체육관', '광부', '윤태용', '문화', '콘텐츠', '산업', '실장', '일', '중국', '우리', '우리나라', '문화', '콘텐츠', '더욱', '중국', '고', '윤', '실장', '날', '연합뉴스', '인터뷰', '중국', '한류', '진출', '및', '성공', '여부', '문화', '외적인', '요소', '콘텐츠', '생산', '유통', '며', '그', '한국', '창의성', '기술', '중국', '자본', '시장', '각각', '장점', '중이', '서로', '협력', '윈윈할', '라며', '한국', '우리', '항상', '중국', '협력', '중', '시한', '메시지', '중국', '측', '게', '고', '전체', '기사', '본문', '배너', '두', '나라', '외부', '요인', '약간', '오해', '잠깐', '문화', '경제', '측면', '안목', '미래', '지향', '시각', '견지해', '한국', '중국', '언론', '중국', '한류', '제동', '관련', '보도', '반복', '재생산', '대해', '그', '실제', '과', '측면', '적지', '중', '문화', '예술', '교류', '신뢰', '국민', '업계', '우려', '고', '그', '또', '최근', '사드', '여파', '양국', '분위기', '속', '극히', '일부', '한류', '행사', '일정', '조금', '대부분', '취소', '정상', '알', '며', '며', '국내', '언론', '끼리', '한국', '중국', '언론', '식', '취재', '경쟁', '건', '양국', '발전', '도움', '안', '고', '윤', '실장', '문화', '예술', '분야', '공공', '부문', '선도', '중국

In [ ]:
from konlpy.corpus import kobill

<h1> 연어(collocation) 찾기</h1>

In [9]:
from konlpy.corpus import kolaw
from konlpy.utils import pprint
from nltk import collocations
from konlpy.tag import Kkma

measures = collocations.BigramAssocMeasures()
#doc = kolaw.open('constitution.txt').read()
doc = open('대통령취임사.txt','r').read()
print('\nCollocations among tagged words:')

tagged_words = Kkma().pos(doc)
finder = collocations.BigramCollocationFinder.from_words(tagged_words)
pprint(finder.nbest(measures.pmi, 10)) # top 5 n-grams with highest PMI

print('\nCollocations among words:')
words = [w for w, t in tagged_words]
ignored_words = [u'안녕']
finder = collocations.BigramCollocationFinder.from_words(words)

finder.apply_word_filter(lambda w: len(w) < 2 or w in ignored_words)
finder.apply_freq_filter(3) # only bigrams that appear 3+ times
pprint(finder.nbest(measures.pmi, 10))

print('\nCollocations among tags:')
tags = [t for w, t in tagged_words]
finder = collocations.BigramCollocationFinder.from_words(tags)
pprint(finder.nbest(measures.pmi, 5))


Collocations among tagged words:
[(('21', 'NR'), ('세기', 'NNG')),
 (('5', 'NR'), ('천', 'NR')),
 (('·', 'SP'), ('무형', 'NNG')),
 (('각종', 'NNG'), ('불공정', 'NNG')),
 (('경축', 'NNG'), ('사절', 'NNG')),
 (('계와', 'MAG'), ('품앗이', 'NNG')),
 (('그리고', 'MAG'), ('이러하', 'VA')),
 (('근심', 'NNG'), ('없이', 'MAG')),
 (('글로', 'MAG'), ('벌', 'VV')),
 (('남북', 'NNG'), ('간', 'NNB'))]

Collocations among words:
[('과학', '기술'),
 ('문화', '융성'),
 ('경제', '부흥'),
 ('창조', '경제'),
 ('국가', '발전'),
 ('바라', 'ㅂ니다'),
 ('국민', '여러분'),
 ('국민', '여러'),
 ('행복', '시대'),
 ('우리', '대한민국')]

Collocations among tags:
[('XR', 'XSA'), ('NR', 'NNM'), ('JC', 'OL'), ('MAC', 'SS'), ('VXV', 'EPH')]


In [7]:
measures = collocations.TrigramAssocMeasures()
#doc = kolaw.open('constitution.txt').read()
doc = open('대통령취임사.txt','r').read()
print('\nCollocations among tagged words:')

tagged_words = Kkma().pos(doc)
finder = collocations.TrigramCollocationFinder.from_words(tagged_words)
pprint(finder.nbest(measures.pmi, 10)) # top 5 n-grams with highest PMI

print('\nCollocations among words:')
words = [w for w, t in tagged_words]
ignored_words = [u'안녕']
finder = collocations.TrigramCollocationFinder.from_words(words)

finder.apply_word_filter(lambda w: len(w) < 2 or w in ignored_words)
finder.apply_freq_filter(3) # only bigrams that appear 3+ times
pprint(finder.nbest(measures.pmi, 10))

print('\nCollocations among tags:')
tags = [t for w, t in tagged_words]
finder = collocations.TrigramCollocationFinder.from_words(tags)
pprint(finder.nbest(measures.pmi, 5))


Collocations among tagged words:
[(('5', 'NR'), ('천', 'NR'), ('년', 'NNB')),
 (('년', 'NNB'), ('유', 'NNG'), ('·', 'SP')),
 (('드립', 'NNG'), ('니', 'VV'), ('다', 'ECS')),
 (('밤새', 'NNG'), ('불이', 'NNG'), ('꺼지', 'VV')),
 (('부탁', 'NNG'), ('드립', 'NNG'), ('니', 'VV')),
 (('여성', 'NNG'), ('이나', 'JC'), ('장애인', 'NNG')),
 (('영하', 'NNG'), ('수십', 'NR'), ('도', 'NNM')),
 (('유', 'NNG'), ('·', 'SP'), ('무형', 'NNG')),
 (('이나', 'JC'), ('장애인', 'NNG'), ('또는', 'MAG')),
 (('이상', 'NNG'), ('핵과', 'NNG'), ('미사일', 'NNG'))]

Collocations among words:
[('국민', '행복', '시대')]

Collocations among tags:
[('VXV', 'EPH', 'ETN'),
 ('XR', 'XSA', 'ETN'),
 ('SP', 'MAC', 'SS'),
 ('SS', 'SP', 'MAC'),
 ('ECS', 'VXV', 'EPH')]
